name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x, 1.25.x, 1.26.x]
        libseccomp: ["v2.3.3", "v2.4.4", "v2.5.6", "v2.6.1", "HEAD"]
        os: [ubuntu-24.04, ubuntu-24.04-arm]

    env:
      LATEST_RELEASED_LIBSECCOMP: v2.6.1

    runs-on: ${{ matrix.os }}

    steps:

    - name: checkout
      uses: actions/checkout@v6

    - name: install libseccomp and its build deps
      run: |
        sudo apt -qq update
        sudo apt -qq install libseccomp2 gperf

    - name: build libseccomp ${{ matrix.libseccomp }}
      uses: ./.github/actions/build-libseccomp
      with:
        version: ${{ matrix.libseccomp }}

    - name: install go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        # Add libseccomp.pc path so that setup-go adds this file hash to cache key.
        # This way, we'll have different caches for different libseccomp versions.
        cache-dependency-path: |
          go.sum
          ${{ env.PKG_CONFIG_LIBDIR }}/libseccomp.pc

    - name: build
      run: make check-build

    - name: test
      run: make test

    - name: test with system libseccomp
      run: |
        unset LD_PRELOAD PKG_CONFIG_LIBDIR
        export _EXPECTED_LIBSECCOMP_VERSION="$(dpkg-query -W -f='${Version}' libseccomp2 | sed -E 's/^[0-9]+://; s/-[^-]*$//')"
        make test-run

    - name: build the latest released libseccomp
      if: matrix.libseccomp != env.LATEST_RELEASED_LIBSECCOMP
      uses: ./.github/actions/build-libseccomp
      with:
        version: ${{ env.LATEST_RELEASED_LIBSECCOMP }}

    - name: test with latest released libseccomp
      if: matrix.libseccomp != env.LATEST_RELEASED_LIBSECCOMP
      # Run the test (pre-built with other seccomp version above).
      run: make test-run

  all-done:
    needs:
      - test
    runs-on: ubuntu-24.04
    steps:
    - run: echo "All jobs completed"
