name: validate
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - release-*
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt -q update
          sudo apt -q install libseccomp-dev
    - name: install go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
        cache: false # golangci-lint uses own caching
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  codespell:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      # Version of codespell bundled with Ubuntu is way old, so use pip.
      run: pip install codespell
    - name: run codespell
      run: codespell
